### ISSUE TITLE
Cant set manual_pass

### ISSUE THREAD

**Issue by pwnmactep** [intelligentguy/pyPrivnote#1]
Hello 

if i try to create a Privenote without a password  with 

> import pyPrivnote as pn
>note_link = pn.create_note("Super secret message")
>print note_link

everything works fine , but if i add a manual password  :

>import pyPrivnote as pn
>note_link = pn.create_note("Super secret message", manual_pass="12345")
>print note_link

i get Error :

`C:\Users\B0X\Desktop\PyPrivn0te>python "privnote - simple.py"
Traceback (most recent call last):
  File "privnote - simple.py", line 3, in <module>
    note_link = pn.create_note("Super secret message", manual_pass="12345")
  File "C:\Python27\lib\site-packages\pyPrivnote\__init__.py", line 41, in create_note
    ask_confirm, notify_email, email_ref_name)
  File "C:\Python27\lib\site-packages\pyPrivnote\model.py", line 177, in set_settings
    self.password = password
  File "C:\Python27\lib\site-packages\pyPrivnote\model.py", line 33, in password
    self._password = bytes(value, encoding="utf-8")
TypeError: str() takes at most 1 argument (2 given)`

heave u an idea how to fix this error ?

**Comment by glebzaripov** [comment]
Hello, python 2 friend. A reason of Exception you get is python 2 str object is completely different then python 3 one. I tried fix it in new version. I would appreciate feedback

**Comment by pwnmactep** [comment]
sorry i was at a world trip .... works like a charm... ty  Gleb

Am Mo., 22. Juli 2019 um 19:40 Uhr schrieb Gleb Zaripov <
notifications@github.com>:
